### ISSUE TITLE
Trocar nome do github para o padrão da comunidade

### ISSUE THREAD

**Issue by aureliosaraiva** [EmberJSBrasil/notes#2]
## Contexto

Hoje o nome da comunidade está como `EmberJSBrasil` e está fora do padrão de todos os projetos Ember.
- `ember-cli-deploy`
- `ember-cli`
- `ember-engine`
- `ember-learning`
- ...

Não existe problema em manter, porém foge bastante de como a comunidade Ember funciona.

## Proposta

Trocar o nome para `ember-brasil` que é próximo dos padrões da comunidade.

**Comment by danilovaz** [comment]
Concordo, faria mais sentido!

**Comment by jeanlucaslima** [comment]
Já que já foi mudado, foi concluir.
